services:
  app:
    build:
      context: .
      dockerfile: _docker/client/Dockerfile
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - "./_docker/client/nginx.conf://etc/nginx/nginx.conf:ro"
